import { Person, Debt } from '@/types';

export const mockPeople: Person[] = [
  { id: '1', name: 'Bruna', createdAt: new Date('2024-01-15') },
  { id: '2', name: 'Kaik', createdAt: new Date('2024-01-20') },
  { id: '3', name: 'Lucas', createdAt: new Date('2024-02-01') },
  { id: '4', name: 'Ana', createdAt: new Date('2024-02-10') },
  { id: '5', name: 'Pedro', createdAt: new Date('2024-03-01') },
];

export const mockDebts: Debt[] = [
  {
    id: '1',
    personId: '1',
    personName: 'Bruna',
    amount: 79,
    description: 'Jantar no restaurante',
    category: 'Pix',
    dueDate: new Date('2024-12-15'),
    createdAt: new Date('2024-12-01'),
    status: 'pending',
  },
  {
    id: '2',
    personId: '2',
    personName: 'Kaik',
    amount: 79,
    description: 'Jantar no restaurante',
    category: 'Pix',
    dueDate: new Date('2024-12-15'),
    createdAt: new Date('2024-12-01'),
    status: 'pending',
  },
  {
    id: '3',
    personId: '3',
    personName: 'Lucas',
    amount: 150,
    description: 'Compras no mercado',
    category: 'Mercado Pago',
    dueDate: new Date('2024-12-20'),
    createdAt: new Date('2024-12-05'),
    status: 'pending',
  },
  {
    id: '4',
    personId: '4',
    personName: 'Ana',
    amount: 200,
    description: 'Ingresso do show',
    category: 'Nubank',
    dueDate: new Date('2024-11-30'),
    createdAt: new Date('2024-11-15'),
    paidAt: new Date('2024-11-28'),
    status: 'paid',
  },
  {
    id: '5',
    personId: '5',
    personName: 'Pedro',
    amount: 50,
    description: 'Uber dividido',
    category: 'Pix',
    dueDate: new Date('2024-12-10'),
    createdAt: new Date('2024-12-08'),
    status: 'pending',
  },
  {
    id: '6',
    personId: '1',
    personName: 'Bruna',
    amount: 120,
    description: 'Cinema e pipoca',
    category: 'Pix',
    dueDate: new Date('2024-11-25'),
    createdAt: new Date('2024-11-20'),
    paidAt: new Date('2024-11-24'),
    status: 'paid',
  },
];

export const categories = [
  'Pix',
  'Nubank',
  'Mercado Pago',
  'PicPay',
  'Transferência',
  'Dinheiro',
  'Outro',
];
